trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - main
      - develop

jobs:
  - job: BuildAndTest
    strategy:
      matrix:
        Windows:
          imageName: windows-latest
        Linux:
          imageName: ubuntu-latest
        macOS:
          imageName: macos-latest

    pool:
      vmImage: $(imageName)

    steps:
      - task: UseDotNet@2
        displayName: Use .NET SDK
        inputs:
          packageType: sdk
          version: 10.0.x
          includePreviewVersions: false

      - script: dotnet restore Akode.DocxGen.sln --locked-mode
        displayName: Restore

      - script: dotnet build Akode.DocxGen.sln --configuration Release --no-restore
        displayName: Build

      - script: dotnet test Akode.DocxGen.sln --configuration Release --no-build
        displayName: Test
