<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocxTemplater" />
    <PackageReference Include="DocxTemplater.Markdown" />
    <PackageReference Include="DocumentFormat.OpenXml" />
  </ItemGroup>
</Project>
